<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLe1hhw7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLe1hhw7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLe1hhw7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLe1hhw7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLe1hhw7\appDevDebugProjectContainer([
    'container.build_hash' => 'Le1hhw7',
    'container.build_id' => '314f8f87',
    'container.build_time' => 1572538446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLe1hhw7');
